# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='course',
        ),
        migrations.AddField(
            model_name='details',
            name='course',
            field=models.ManyToManyField(related_name='Detail', to='student.Course'),
        ),
    ]
